// Every icon the site renders, imported by name so only these end up in the
// bundle. Namespace imports of react-icons/si pull in the whole pack (~2 MB).
// Add an entry here when data.ts references a new icon; the renderer falls back
// to a neutral glyph for unknown names.
import type { IconType } from 'react-icons';
import { DiHeroku } from 'react-icons/di';
import { FaAws, FaLinkedin, FaSlack } from 'react-icons/fa';
import { FiMail } from 'react-icons/fi';
import {
  SiAntdesign,
  SiBitbucket,
  SiBootstrap,
  SiClickup,
  SiCloudinary,
  SiCouchbase,
  SiDatadog,
  SiDigitalocean,
  SiDiscord,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiFiverr,
  SiGit,
  SiGithub,
  SiGitlab,
  SiJavascript,
  SiJira,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNotion,
  SiOkta,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPycharm,
  SiPython,
  SiReact,
  SiRedis,
  SiShadcnui,
  SiStrapi,
  SiSupabase,
  SiSwagger,
  SiTailwindcss,
  SiTerraform,
  SiTrello,
  SiTypescript,
  SiUpwork,
  SiVercel,
} from 'react-icons/si';
import { VscVscode } from 'react-icons/vsc';

export const icons: Record<string, IconType> = {
  FiMail,
  SiAmazonaws: FaAws,
  SiAmazondynamodb: FaAws,
  SiAmazons3: FaAws,
  SiAntdesign,
  SiBitbucket,
  SiBootstrap,
  SiClickup,
  SiCloudinary,
  SiCouchbase,
  SiDatadog,
  SiDigitalocean,
  SiDiscord,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiFiverr,
  SiGit,
  SiGithub,
  SiGitlab,
  SiHeroku: DiHeroku,
  SiJavascript,
  SiJira,
  SiLinkedin: FaLinkedin,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNotion,
  SiOkta,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPycharm,
  SiPython,
  SiReact,
  SiRedis,
  SiShadcnui,
  SiSlack: FaSlack,
  SiStrapi,
  SiSupabase,
  SiSwagger,
  SiTailwindcss,
  SiTerraform,
  SiTrello,
  SiTypescript,
  SiUpwork,
  SiVercel,
  SiVisualstudiocode: VscVscode,
};
